config/routes.rb
Rails.application.routes.draw do
  resources :recipes
  resources :songs
  resources :categories

  root 'categories#index'

  get 'tag_recipes' => 'recipes#tag_recipes'
  get 'categorical' => 'categories#recipes_by_category'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

	has_many :recipes
	
end

app/models/recipe.rb
class Recipe < ApplicationRecord

	belongs_to :category

	has_many :recipe_tags
	has_many :tags, through: :recipe_tags

	has_one_attached :image
end

app/models/recipe_tag.rb
class RecipeTag < ApplicationRecord
end

app/models/song.rb
class Song < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :recipe_tags
	has_many :recipes, through: :recipe_tags
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :categories, :tag

	def categories
		@categories = Category.all
	end

	def tag 
		@tag = Tag.all
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
    @tag = Tag.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def recipes_by_category
    @category = Category.find(params[:cat_id])
    @recipes = Recipe.all
    @recipes_by_cat = []

    @recipes.each do |recipe|
      if recipe.category.id == @category.id
        @recipes_by_cat.push(recipe)
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  include RecipesHelper
  # GET /recipes
  # GET /recipes.json

def tag_recipes
  # @tag = Tag.find(params[:cat_id])
  # @recipes = Recipe.all
  # @recipes_by_tag = []

  # @recipes.each do |recipe|
  #   if recipe.keyword == @tag.id
  #     @recipes_by_tag.push(recipe)
  #   end
  # end
  # puts @recipes_by_tag
  @tag = Tag.all
  @tags = Tag.find(params[:tag_id])
  @recipes = Recipe.all
  @rtag = RecipeTag.all
  @recipes_by_tag = []

  @rtag.each do |rtag|
    if rtag.tag_id == @tags.id
      recipe = Recipe.find(rtag.recipe_id)
      @recipes_by_tag.push(recipe)
    end
  end






end



  def index
    @recipes = Recipe.all
    @category = Category.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
    @categories = Category.all
  end

  # GET /recipes/1/edit
  def edit
    @categories = Category.all
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        @recipe = get_tagged(@recipe)
        @recipe.save

        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:name, :category_id, :description, :ingredients, :directions, :image, :song, :keyword)
    end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.all
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: 'Song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper

	def get_tagged(recipes)
		keyword_arr = @recipe.keyword.split

        keyword_arr.each do |word|
	      	if word[0] == "#"
	        	if Tag.pluck(:phrase).include?(word)
	          		tag = Tag.find_by(phrase: word)
	        	else
	          		tag = Tag.create(phrase: word)
	        	end
	        	recipe_tag = RecipeTag.create(recipe_id: @recipe.id, tag_id: tag.id)
	        	# keyword_arr[index] = "<a href='/tag_recipes?id=#{tag.id}'>#{word}</a>"
	       	end
     	end
      	recipes.keyword = keyword_arr.join(" ")
      	return recipes
    end

end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<!-- will need to link the images to the category partial -->


<div class="grid-container">
  <div class="title">
  <%=image_tag("mainlogo.png")%>
  </div>
  <% @categories.each do |category| %>
  <div class="aps">
    <%= link_to image_tag("apps.png", size: "200x200"), categorical_path(cat_id: category.id = 1) %>
  </div>
  <div class="diner">
    <%= link_to image_tag("dinner.png", size: "200x200"), categorical_path(cat_id: category.id = 2)%>
  </div>
  <div class="breakfast">
    <%= link_to image_tag("breakfast.png", size: "200x200"), categorical_path(cat_id: category.id = 3)%>
  </div>
  <div class="desert">
    <%= link_to image_tag("dessert.png", size: "200x200"), categorical_path(cat_id: category.id = 4)%>
  </div>
  <div class="drinks">
    <%= link_to image_tag("drinks.png", size: "200x200"), categorical_path(cat_id: category.id = 5)%>
  </div>
  <% end %>
  <div class="mainlogo">
  <span class="typed"><p id="typer"></p> </span>
  <span class="typed"><p id="backtyper"></p> </span>
  </div>
  <!-- <div class="mainlogo">
  <%=image_tag("design.png") %>
  </div> -->
</div>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/recipes_by_category.html.erb
<h1><%= @category.name %></h1>
<div class="row">
  <% @recipes_by_cat.each do |recipe| %>

    <div class="col-sm-6 col-md-4">
      <div class="well text-center">
        <% if recipe.image.nil? == false %>
          <p><%= image_tag recipe.image, size: 250 %></p>
        <% end %>
        <div class="recipe-name">
        <h3><%= recipe.name %></h3>
        </div>
        <p>
          <a href="#" data-toggle="modal" data-target="#myModal_<%= recipe.id %>">
            <span class="glyphicon "></span>View Recipe</a>
        </p>
      </div>
    </div>

    <!-- Recipe Modal -->

    <div class="recipe-modal">

      <div class="modal fade" id="myModal_<%= recipe.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span></button>
              <h3 class="modal-title" id="myModalLabel"><%= recipe.name %> <div style="text-align: center"> <%= recipe.song.html_safe %>
              </div></h3>
            </div>
            <div class="modal-body">
              <div class="modal-image">
                <% if recipe.image.nil? == false %>
                  <p><%= image_tag recipe.image, size: 150 %></p>
                <% end %>
              </div>
              <p>
                <strong>Description:</strong>
                <%= recipe.description%></p>
              <p>
                <strong>Ingredients:</strong>
                <%= recipe.ingredients.html_safe %></p>
              <p>
                <strong>Directions:</strong>
                <%= recipe.directions.html_safe %></p>

            </div>

          </div>
        </div>
      </div>
    </div>



  <% end %>
</div>

</div>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/_navbar.html.erb
<nav>
  <div id="nav-logo">
    <%= link_to root_path do %>
     <%=image_tag("sdlogo2.png", size: "50x50")%>
  <% end %>
 </div>
  <div class="category">
   <span> CATEGORIES </span>
   <div class="category-content">

    <% counter = 0 %>
    <% @categories.each do |category| %>
    <% counter += 1 %>
      <li><%= link_to category.name, categorical_path(cat_id: category.id = counter) %></li>
    <% end %>



   </div>
 </div>

  <div class="tags">
    <span> TAGS <i class="fa fa-hashtag" aria-hidden="true"></i></span>
    <div class="tags-content">
    <% @tag.each do |tag| %>
      <li><%= link_to tag.phrase, tag_recipes_path(tag_id: tag.id) %></li>
    <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestProjectNew</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
  </head>

<body>
  <!-- <body onload="typeWriter();""backwards();"> -->
    <%= render 'layouts/navbar' %>

    <%= yield %>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_with(model: recipe, local: true) do |form| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

   <div class="field">
    <%= form.label :category_id %>
    <%= form.select(:category_id, @categories.collect{ |c| [c.name, c.id]}, {include_blank: "Select Category"}, required: true) %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :ingredients %>
    <%= form.text_area :ingredients %>
  </div>

  <div class="field">
    <%= form.label :directions %>
    <%= form.text_area :directions %>
  </div>

  <div class="field">
    <%= form.label :song %>
    <%= form.text_area :song %>
  </div>

  <div class="field">
    <%= form.label :keyword %>
    <%= form.text_area :keyword %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>



  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recipes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Category</th>
      <th>Description</th>
      <th>Ingredients</th>
      <th>Directions</th>
      <th>Song</th>
      <th>Image</th>
      <th>Tag</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= recipe.name %></td>
        <td><%= recipe.category.name %></td>
        <td><%= recipe.description.html_safe %></td>
        <td><%= recipe.ingredients %></td>
        <td><%= recipe.directions.html_safe %></td>
        <td><%= recipe.song.html_safe %></td>
        <td><%= recipe.keyword.html_safe %></td>
        <td><%= recipe.image %></td>
        <td><%= link_to 'Show', recipe %></td>
        <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
        <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipe', new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form', recipe: @recipe %>


<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @recipe.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @recipe.category.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @recipe.description %>
</p>

<p>
  <strong>Ingredients:</strong>
  <%= @recipe.ingredients.html_safe %>
</p>

<p>
  <strong>Song:</strong>
  <%= @recipe.song.html_safe %>
</p>

<p>
  <strong>Directions:</strong>
  <%= @recipe.directions.html_safe %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @recipe.keyword.html_safe %>
</p>


<p> <%= image_tag @recipe.image, size: 200 %></p>


<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/tag_recipes.html.erb
<h1><%= @tags.phrase %></h1>
<div class="row">
  <% @recipes_by_tag.each do |recipe| %>

    <div class="col-sm-6 col-md-4">
      <div class="well text-center">
        <% if recipe.image.nil? == false %>
          <p><%= image_tag recipe.image, size: 250 %></p>
        <% end %>
        <div class="recipe-name">
        <h3><%= recipe.name %></h3>
        </div>
        <p>
          <a href="#" data-toggle="modal" data-target="#myModal_<%= recipe.id %>">
            <span class="glyphicon "></span>View Recipe</a>
        </p>
      </div>
    </div>

    <!-- Recipe Modal -->

    <div class="recipe-modal">

      <div class="modal fade" id="myModal_<%= recipe.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span></button>
              <h3 class="modal-title" id="myModalLabel"><%= recipe.name %> <div style="text-align: center"> <%= recipe.song.html_safe %>
              </div></h3>
            </div>
            <div class="modal-body">
              <div class="modal-image">
                <% if recipe.image.nil? == false %>
                  <p><%= image_tag recipe.image, size: 150 %></p>
                <% end %>
              </div>
              <p>
                <strong>Description:</strong>
                <%= recipe.description%></p>
              <p>
                <strong>Ingredients:</strong>
                <%= recipe.ingredients.html_safe %></p>
              <p>
                <strong>Directions:</strong>
                <%= recipe.directions.html_safe %></p>

            </div>

          </div>
        </div>
      </div>
      <% end %>
    </div>

app/views/songs/_form.html.erb
<%= form_with(model: song, local: true) do |form| %>
  <% if song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% song.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/songs/edit.html.erb
<h1>Editing Song</h1>

<%= render 'form', song: @song %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Songs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @songs.each do |song| %>
      <tr>
        <td><%= song.title %></td>
        <td><%= link_to 'Show', song %></td>
        <td><%= link_to 'Edit', edit_song_path(song) %></td>
        <td><%= link_to 'Destroy', song, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Song', new_song_path %>

app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render 'form', song: @song %>

<%= link_to 'Back', songs_path %>

app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @song.title %>
</p>

<%= link_to 'Edit', edit_song_path(@song) %> |
<%= link_to 'Back', songs_path %>